---
name: Deploy Terraform

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, x64]  # Usando self-hosted para que você possa personalizar o ambiente, se necessário
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest  # Usando a versão mais recente do Terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
