---
name: Deploy Terraform
on:
    push:
        branches: [ main ]
    
jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted, linux, x64]
        steps:
        - name: Checkout
          uses: actions/checkout@v3